site_name: Open Front End

theme:
  name: material
  custom_dir: theme/custom
  palette:
    primary: custom
  font:
    text: Nunito
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    logo: material/lan

plugins:
  - search

nav:
  - Home: index.md
  - Users:
    - User Guide: users/user_guide.md
    - Workbench User Guide: users/workbench_user_guide.md
  - Admins:
    - Admin Guide: admins/admin_guide.md
    - Advanced Admin Guide: admins/advanced_admin_guide.md
    - Cluster Guide: admins/cluster_guide.md
    - Application Guide: admins/application_guide.md
    - Workbench Admin Guide: admins/workbench_admin_guide.md
  - Developers:
    - Developer Guide: developers/developer_guide.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.7.3/lottie.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - sane_lists
